package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Entity class representing a meeting room booking.
 * <p>
 * This entity stores booking information including the room ID, date, start
 * time, and end time.
 * Bookings are persisted in the "bookings" table in the database.
 * </p>
 *
 * @author Tharinda Rajapaksha
 * @version 1.0.0
 */
@Entity
@Table(name = "bookings")
@Getter
@Setter
@NoArgsConstructor
public class Booking {

    /**
     * Unique identifier for the booking.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the meeting room being booked.
     */
    @Column(nullable = false)
    private String roomName;

    /**
     * The description of the booking.
     */
    @Column(nullable = false)
    private String description;

    /**
     * The date of the booking.
     * Format: YYYY-MM-DD
     */
    @Column(nullable = false)
    private LocalDate date;

    /**
     * The start time of the booking.
     * Format: HH:mm
     */
    @Column(nullable = false)
    private LocalTime startTime;

    /**
     * The end time of the booking.
     * Format: HH:mm
     * Must be after the start time.
     */
    @Column(nullable = false)
    private LocalTime endTime;

    /**
     * Constructor for creating a new booking without an ID.
     * The ID will be auto-generated by the database.
     *
     * @param roomName    the name of the room to book
     * @param description the description of the booking
     * @param date        the date of the booking
     * @param startTime   the start time of the booking
     * @param endTime     the end time of the booking
     */
    public Booking(String roomName, String description, LocalDate date, LocalTime startTime, LocalTime endTime) {
        this.roomName = roomName;
        this.description = description;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
    }
}
